### ISSUE TITLE
一接受消息就报错

### ISSUE THREAD

**Issue by StiffFy** [HanSon/my-vbot#2]
PHP Fatal error:  Uncaught Predis\Connection\ConnectionException: PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalErrorException' not found in D:\php\my-vbot\vendor\hanson\vbot\src\Foundation\ExceptionHandler.php:180
Stack trace:
#0 D:\php\my-vbot\vendor\hanson\vbot\src\Foundation\ExceptionHandler.php(164): Hanson\Vbot\Foundation\ExceptionHandler->fatalExceptionFromError(Array, 0)
#1 [internal function]: Hanson\Vbot\Foundation\ExceptionHandler->handleShutdown()
#2 {main}
  thrown in D:\php\my-vbot\vendor\hanson\vbot\src\Foundation\ExceptionHandler.php on line 180

Fatal error: Uncaught Error: Class 'Symfony\Component\Debug\Exception\FatalErrorException' not found in D:\php\my-vbot\vendor\hanson\vbot\src\Foundation\ExceptionHandler.php:180
Stack trace:
#0 D:\php\my-vbot\vendor\hanson\vbot\src\Foundation\ExceptionHandler.php(164): Hanson\Vbot\Foundation\ExceptionHandler->fatalExceptionFromError(Array, 0)
#1 [internal function]: Hanson\Vbot\Foundation\ExceptionHandler->handleShutdown()
#2 {main}
  thrown in D:\php\my-vbot\vendor\hanson\vbot\src\Foundation\ExceptionHandler.php on line 180

**Comment by Hanson** [comment]
用新版还是这个报错吗？

而且这个报错是你的 message Handler 有问题

**Comment by StiffFy** [comment]
要升级吗？我是直接跑你这个demo的

**Comment by legeng** [comment]
同样问题i，按照你的步骤来。扫描后直接报错

**Comment by lscho** [comment]
报错是缺少symfony/debug组件，执行`composer require symfony/debug`安装一下就可以
